[package]
name = "wsclient"
version = "0.1.0"
authors = ["manpat <pat@patsown.com>"]
build = "../build.rs"

[features]
default = ["client"]
client = []

[build-dependencies]
gl_generator = "0.5.0"

[dependencies]
libc = { version = "0.2", default-features = false }
common = { path = "../common" }
