[package]
name = "wsserver"
version = "0.1.0"
authors = ["manpat <pat@patsown.com>"]
build = "../build.rs"

[dependencies]
sha1 = "0.2.0"
base64 = "0.6.0"
flate2 = "0.2"
common = { path = "../common" }